import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export const sleep = (ms: number) =>
  new Promise((resolve) => setTimeout(resolve, ms));

export const USER_ROLES = ['user', 'admin', 'guest', 'staff'] as const;
export const MONTH_NAMES = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
] as const;

export const COUNTRIES = [
  { name: 'Afghanistan', nativeName: 'افغانستان', code: 'AF' },
  { name: 'Albania', nativeName: 'Shqipëri', code: 'AL' },
  { name: 'Algeria', nativeName: 'الجزائر', code: 'DZ' },
  { name: 'Andorra', nativeName: 'Andorra', code: 'AD' },
  { name: 'Angola', nativeName: 'Angola', code: 'AO' },
  { name: 'Argentina', nativeName: 'Argentina', code: 'AR' },
  { name: 'Armenia', nativeName: 'Հայաստան', code: 'AM' },
  { name: 'Australia', nativeName: 'Australia', code: 'AU' },
  { name: 'Austria', nativeName: 'Österreich', code: 'AT' },
  { name: 'Azerbaijan', nativeName: 'Azərbaycan', code: 'AZ' },
  { name: 'Bahrain', nativeName: 'البحرين', code: 'BH' },
  { name: 'Bangladesh', nativeName: 'বাংলাদেশ', code: 'BD' },
  { name: 'Belarus', nativeName: 'Беларусь', code: 'BY' },
  { name: 'Belgium', nativeName: 'België', code: 'BE' },
  { name: 'Belize', nativeName: 'Belize', code: 'BZ' },
  { name: 'Benin', nativeName: 'Bénin', code: 'BJ' },
  { name: 'Bhutan', nativeName: 'འབྲུག', code: 'BT' },
  { name: 'Bolivia', nativeName: 'Bolivia', code: 'BO' },
  {
    name: 'Bosnia and Herzegovina',
    nativeName: 'Bosna i Hercegovina',
    code: 'BA',
  },
  { name: 'Botswana', nativeName: 'Botswana', code: 'BW' },
  { name: 'Brazil', nativeName: 'Brasil', code: 'BR' },
  { name: 'Bulgaria', nativeName: 'България', code: 'BG' },
  { name: 'Burkina Faso', nativeName: 'Burkina Faso', code: 'BF' },
  { name: 'Cambodia', nativeName: 'កម្ពុជា', code: 'KH' },
  { name: 'Cameroon', nativeName: 'Cameroun', code: 'CM' },
  { name: 'Canada', nativeName: 'Canada', code: 'CA' },
  { name: 'Chile', nativeName: 'Chile', code: 'CL' },
  { name: 'China', nativeName: '中国', code: 'CN' },
  { name: 'Colombia', nativeName: 'Colombia', code: 'CO' },
  { name: 'Costa Rica', nativeName: 'Costa Rica', code: 'CR' },
  { name: 'Croatia', nativeName: 'Hrvatska', code: 'HR' },
  { name: 'Cuba', nativeName: 'Cuba', code: 'CU' },
  { name: 'Cyprus', nativeName: 'Κύπρος', code: 'CY' },
  { name: 'Czech Republic', nativeName: 'Česká republika', code: 'CZ' },
  { name: 'Denmark', nativeName: 'Danmark', code: 'DK' },
  {
    name: 'Dominican Republic',
    nativeName: 'República Dominicana',
    code: 'DO',
  },
  { name: 'Egypt', nativeName: 'مصر', code: 'EG' },
  { name: 'El Salvador', nativeName: 'El Salvador', code: 'SV' },
  { name: 'Estonia', nativeName: 'Eesti', code: 'EE' },
  { name: 'Ethiopia', nativeName: 'ኢትዮጵያ', code: 'ET' },
  { name: 'Finland', nativeName: 'Suomi', code: 'FI' },
  { name: 'France', nativeName: 'France', code: 'FR' },
  { name: 'Georgia', nativeName: 'საქართველო', code: 'GE' },
  { name: 'Germany', nativeName: 'Deutschland', code: 'DE' },
  { name: 'Greece', nativeName: 'Ελλάδα', code: 'GR' },
  { name: 'Greenland', nativeName: 'Kalaallit Nunaat', code: 'GL' },
  { name: 'Guatemala', nativeName: 'Guatemala', code: 'GT' },
  { name: 'Honduras', nativeName: 'Honduras', code: 'HN' },
  { name: 'Hungary', nativeName: 'Magyarország', code: 'HU' },
  { name: 'Iceland', nativeName: 'Ísland', code: 'IS' },
  { name: 'India', nativeName: 'भारत', code: 'IN' },
  { name: 'Indonesia', nativeName: 'Indonesia', code: 'ID' },
  { name: 'Iran', nativeName: 'ایران', code: 'IR' },
  { name: 'Iraq', nativeName: 'العراق', code: 'IQ' },
  { name: 'Ireland', nativeName: 'Éire', code: 'IE' },
  { name: 'Israel', nativeName: 'יִשְׂרָאֵל', code: 'IL' },
  { name: 'Italy', nativeName: 'Italia', code: 'IT' },
  { name: 'Jamaica', nativeName: 'Jamaica', code: 'JM' },
  { name: 'Japan', nativeName: '日本', code: 'JP' },
  { name: 'Jordan', nativeName: 'الأردن', code: 'JO' },
  { name: 'Kazakhstan', nativeName: 'Қазақстан', code: 'KZ' },
  { name: 'Kenya', nativeName: 'Kenya', code: 'KE' },
  { name: 'Kuwait', nativeName: 'الكويت', code: 'KW' },
  { name: 'Latvia', nativeName: 'Latvija', code: 'LV' },
  { name: 'Lebanon', nativeName: 'لبنان', code: 'LB' },
  { name: 'Lithuania', nativeName: 'Lietuva', code: 'LT' },
  { name: 'Luxembourg', nativeName: 'Lëtzebuerg', code: 'LU' },
  { name: 'Madagascar', nativeName: 'Madagasikara', code: 'MG' },
  { name: 'Malaysia', nativeName: 'مليسيا', code: 'MY' },
  { name: 'Maldives', nativeName: 'ދިވެހިރާއްޖޭގެ', code: 'MV' },
  { name: 'Mexico', nativeName: 'México', code: 'MX' },
  { name: 'Mongolia', nativeName: 'Монгол', code: 'MN' },
  { name: 'Morocco', nativeName: 'المغرب', code: 'MA' },
  { name: 'Nepal', nativeName: 'नेपाल', code: 'NP' },
  { name: 'Netherlands', nativeName: 'Nederland', code: 'NL' },
  { name: 'New Zealand', nativeName: 'Aotearoa', code: 'NZ' },
  { name: 'Nicaragua', nativeName: 'Nicaragua', code: 'NI' },
  { name: 'Nigeria', nativeName: 'Nigeria', code: 'NG' },
  { name: 'Norway', nativeName: 'Norge', code: 'NO' },
  { name: 'Oman', nativeName: 'عمان', code: 'OM' },
  { name: 'Pakistan', nativeName: 'پاکستان', code: 'PK' },
  { name: 'Panama', nativeName: 'Panamá', code: 'PA' },
  { name: 'Paraguay', nativeName: 'Paraguay', code: 'PY' },
  { name: 'Peru', nativeName: 'Perú', code: 'PE' },
  { name: 'Philippines', nativeName: 'Pilipinas', code: 'PH' },
  { name: 'Poland', nativeName: 'Polska', code: 'PL' },
  { name: 'Portugal', nativeName: 'Portugal', code: 'PT' },
  { name: 'Qatar', nativeName: 'قطر', code: 'QA' },
  { name: 'Romania', nativeName: 'România', code: 'RO' },
  { name: 'Russia', nativeName: 'Россия', code: 'RU' },
  { name: 'Saudi Arabia', nativeName: 'المملكة العربية السعودية', code: 'SA' },
  { name: 'Senegal', nativeName: 'Sénégal', code: 'SN' },
  { name: 'Serbia', nativeName: 'Србија', code: 'RS' },
  { name: 'Singapore', nativeName: 'Singapura', code: 'SG' },
  { name: 'Slovakia', nativeName: 'Slovensko', code: 'SK' },
  { name: 'South Africa', nativeName: 'Suid-Afrika', code: 'ZA' },
  { name: 'South Korea', nativeName: '대한민국', code: 'KR' },
  { name: 'Spain', nativeName: 'España', code: 'ES' },
  { name: 'Sri Lanka', nativeName: 'ශ්‍රී ලංකාව', code: 'LK' },
  { name: 'Sudan', nativeName: 'السودان', code: 'SD' },
  { name: 'Sweden', nativeName: 'Sverige', code: 'SE' },
  { name: 'Switzerland', nativeName: 'Schweiz', code: 'CH' },
  { name: 'Syria', nativeName: 'سوريا', code: 'SY' },
  { name: 'Thailand', nativeName: 'ประเทศไทย', code: 'TH' },
  { name: 'Turkey', nativeName: 'Türkiye', code: 'TR' },
  { name: 'Ukraine', nativeName: 'Україна', code: 'UA' },
  {
    name: 'United Arab Emirates',
    nativeName: 'الإمارات العربية المتحدة',
    code: 'AE',
  },
  { name: 'United Kingdom', nativeName: 'United Kingdom', code: 'GB' },
  { name: 'United States', nativeName: 'United States', code: 'US' },
  { name: 'Venezuela', nativeName: 'Venezuela', code: 'VE' },
  { name: 'Vietnam', nativeName: 'Việt Nam', code: 'VN' },
];
